name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        repository: ${{ github.repository }}.wiki
        token: ${{ secrets.pat }}
    - name: check wiki repo content before change
      run: |
        ls -al
    - name: edit wiki
      run: |
        echo test >> test.md
    - name: check wiki repo content after change
      run: |
        ls -al
        
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add changes"
       
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        repository: ${{ github.repository }}.wiki
        github_token: ${{ secrets.pat }}
