name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --no-build --verbosity normal

    - name: Create and navigate to wiki folder
      run: mkdir wiki && cd wiki

    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        repository: ${{ github.repository }}.wiki
        path: wiki
        token: ${{ secrets.pat }}
    - name: check wiki repo content before change
      run: |
        cd wiki && ls -al
    - name: Update wiki
      run: |
        cp ./testing123.UnitTests/coverage.cobertura.xml wiki
    
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@4.8.12
      with:
        reports: ./testing123.UnitTests/coverage.cobertura.xml
        targetdir: wiki
        reporttypes: MarkdownSummary;HtmlInline;MHtml
        
    - name: check wiki repo content after change
      run: |
        cd wiki && ls -al

    - name: Commit files
      run: |
        cd wiki
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add changes"
       
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        repository: ${{ github.repository }}.wiki
        github_token: ${{ secrets.pat }}
        directory: wiki
